#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="kwmserver"

mkdir -p "${CONFIG_PATH}"
configure_logging

print_debug "Configuring KWMServer"
configure_kwmserver
print_debug "Finished Configuring KWMServer"

liftoff
