version: '2.4'
services:

  kwmserver-app:
    image: tiredofit/kopano-kwmserver:latest
    container_name: kwmserver-app
    volumes:
      - ./logs/kwmserver:/logs
      - ./data:/data
      - ./config:/config
      - ./certs:/certs
      - ./assets/custom:/assets/custom
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_LOG_LEVEL=DEBUG
      - DEBUG_MODE=FALSE
      - LOG_LEVEL=DEBUG

      - SERVER_OIDC_IDENTIFIER=https://konnect.example.com
    networks:
      - services
    restart: always

networks:
  services:
    external: true
